name: Build Desk Compass

on:
  push:
    branches:
      - main

jobs:
  prepare:
    container: node:lts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v4
      - run: echo 'yarn-offline-mirror ".yarn-cache/"' >> .yarnrc
      - run: echo 'yarn-offline-mirror-pruning true' >> .yarnrc
      - run: HUSKY=0 yarn install --frozen-lockfile --no-progress
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

  lint:
    runs-on: ubuntu-latest
    needs: [prepare]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
      - run: HUSKY=0 yarn install --frozen-lockfile --no-progress
      - run: yarn lint
      # - run: yarn workspace frontend run check

  unit_test_frontend:
    runs-on: ubuntu-latest
    needs: [prepare]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
      - run: HUSKY=0 yarn install --frozen-lockfile --no-progress
      - run: yarn workspace frontend run test:coverage

  unit_test_backend:
    runs-on: ubuntu-latest
    needs: [prepare]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
      - run: HUSKY=0 yarn install --frozen-lockfile --no-progress
      - run: yarn workspace api run test:coverage

  e2e_test:
    container:
      image: node:lts
      options: --user root
    runs-on: ubuntu-latest
    needs: [prepare]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        run: HUSKY=0 yarn install --frozen-lockfile --no-progress
      - name: Install browsers
        run: npx playwright install-deps && npx playwright install chromium
      - name: Run Playwright tests
        run: yarn e2e
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: workspaces/e2e/playwright-report/
          retention-days: 30

  build_image:
    runs-on: ubuntu-latest
    needs: [lint, unit_test_frontend, unit_test_backend]
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag desk-compass:$(date +%s)

  release:
    runs-on: ubuntu-latest
    needs: [lint, unit_test_frontend, unit_test_backend]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}